/**
 * Auto-generated contract registry
 * Generated by @abiregistry/sdk
 * 
 * Access contracts by network name or chain ID:
 * - contracts.mainnet.MyToken
 * - contracts[1].MyToken
 */

import { contract2Config } from './contract2'

export const contracts = {
  mainnet: {
    Contract2: contract2Config
  },

  // Chain ID aliases (point to same objects)
  1: contracts.mainnet
} as const

// Type helpers
export type Network = keyof typeof contracts
export type ContractsOn<T extends Network> = T extends string | number 
  ? typeof contracts[T] extends object ? keyof typeof contracts[T] : never
  : never

/**
 * Get a contract config with full type safety
 * @example
 * const token = getContract('mainnet', 'MyToken')
 * const sameToken = getContract(1, 'MyToken')  // Same as above
 */
export function getContract<
  TNet extends Network,
  TName extends ContractsOn<TNet>
>(
  network: TNet,
  contractName: TName
): typeof contracts[TNet][TName] {
  return contracts[network][contractName]
}

/**
 * Get all deployments of a contract across networks
 */
export function getContractDeployments(contractName: string) {
  const deployments: Array<{
    network: string
    chainId: number
    config: any
  }> = []
  
  for (const [key, networkContracts] of Object.entries(contracts)) {
    if (typeof key === 'string' && !key.match(/^\d+$/)) {
      const contract = (networkContracts as any)[contractName]
      if (contract) {
        deployments.push({
          network: key,
          chainId: contract.chainId,
          config: contract
        })
      }
    }
  }
  
  return deployments
}
