import type { AbiItem, GeneratedFile } from './types'

export class CodeGenerator {
    private typescript: boolean

    constructor(typescript = true) {
        this.typescript = typescript
    }

    /**
     * Generate files for all ABIs
     */
    generateFiles(abis: AbiItem[]): GeneratedFile[] {
        const files: GeneratedFile[] = []

        // Generate individual ABI files
        for (const abi of abis) {
            files.push(this.generateAbiFile(abi))
        }

        // Generate index file
        files.push(this.generateIndexFile(abis))

        // Generate types file (TypeScript only)
        if (this.typescript) {
            files.push(this.generateTypesFile(abis))
        }

        return files
    }

    /**
     * Generate individual ABI file
     */
    private generateAbiFile(abi: AbiItem): GeneratedFile {
        const fileName = this.sanitizeFileName(abi.contract)
        const ext = this.typescript ? '.ts' : '.js'

        const content = this.typescript
            ? this.generateTypeScriptAbiFile(abi)
            : this.generateJavaScriptAbiFile(abi)

        return {
            path: `${fileName}${ext}`,
            content,
        }
    }

    /**
     * Generate TypeScript ABI file
     */
    private generateTypeScriptAbiFile(abi: AbiItem): string {
        return `/**
 * ${abi.contract}
 * Network: ${abi.network}
 * Chain ID: ${abi.chainId}
 * Address: ${abi.address}
 * Version: ${abi.version}
 */

export const ${this.sanitizeVariableName(abi.contract)}Abi = ${JSON.stringify(abi.abi, null, 2)} as const

export const ${this.sanitizeVariableName(abi.contract)}Address = '${abi.address}' as const

export const ${this.sanitizeVariableName(abi.contract)}ChainId = ${this.getChainIdFromNetwork(abi.network)}

export const ${this.sanitizeVariableName(abi.contract)}Config = {
    address: ${this.sanitizeVariableName(abi.contract)}Address,
    abi: ${this.sanitizeVariableName(abi.contract)}Abi,
    chainId: ${this.sanitizeVariableName(abi.contract)}ChainId,
} as const
`
    }

    /**
     * Generate JavaScript ABI file
     */
    private generateJavaScriptAbiFile(abi: AbiItem): string {
        return `/**
 * ${abi.contract}
 * Network: ${abi.network}
 * Chain ID: ${abi.chainId}
 * Address: ${abi.address}
 * Version: ${abi.version}
 */

export const ${this.sanitizeVariableName(abi.contract)}Abi = ${JSON.stringify(abi.abi, null, 2)}

export const ${this.sanitizeVariableName(abi.contract)}Address = '${abi.address}'

export const ${this.sanitizeVariableName(abi.contract)}ChainId = ${this.getChainIdFromNetwork(abi.network)}

export const ${this.sanitizeVariableName(abi.contract)}Config = {
    address: ${this.sanitizeVariableName(abi.contract)}Address,
    abi: ${this.sanitizeVariableName(abi.contract)}Abi,
    chainId: ${this.sanitizeVariableName(abi.contract)}ChainId,
}
`
    }

    /**
     * Generate index file that exports all ABIs
     */
    private generateIndexFile(abis: AbiItem[]): GeneratedFile {
        const ext = this.typescript ? '.ts' : '.js'
        const exports = abis.map((abi) => {
            const fileName = this.sanitizeFileName(abi.contract)
            return `export * from './${fileName}'`
        })

        const content = `/**
 * Auto-generated ABI exports
 * Generated by @abiregistry/sdk
 */

${exports.join('\n')}
`

        return {
            path: `index${ext}`,
            content,
        }
    }

    /**
     * Generate types file for TypeScript
     */
    private generateTypesFile(abis: AbiItem[]): GeneratedFile {
        const typeDefinitions = abis.map((abi) => {
            const varName = this.sanitizeVariableName(abi.contract)
            return `export type ${varName}Type = typeof import('./${this.sanitizeFileName(abi.contract)}').${varName}Abi`
        })

        const content = `/**
 * Auto-generated types
 * Generated by @abiregistry/sdk
 */

${typeDefinitions.join('\n')}

export type AllAbis = {
${abis.map((abi) => {
            const varName = this.sanitizeVariableName(abi.contract)
            return `    ${varName}: ${varName}Type`
        }).join('\n')}
}
`

        return {
            path: 'types.ts',
            content,
        }
    }

    /**
     * Sanitize contract name for file name
     */
    private sanitizeFileName(name: string): string {
        // Insert hyphens before capital letters (camelCase/PascalCase to kebab-case)
        const withHyphens = name.replace(/([a-z0-9])([A-Z])/g, '$1-$2')

        return withHyphens
            .replace(/[^a-zA-Z0-9-]/g, '-')
            .replace(/-+/g, '-')
            .replace(/^-|-$/g, '')
            .toLowerCase()
    }

    /**
     * Sanitize contract name for variable name
     */
    private sanitizeVariableName(name: string): string {
        // Split on non-alphanumeric characters and capital letters
        const withSpaces = name
            .replace(/([a-z0-9])([A-Z])/g, '$1 $2') // Add space before capitals
            .replace(/[^a-zA-Z0-9]/g, ' ') // Replace special chars with spaces

        const words = withSpaces.split(' ').filter(Boolean)

        if (words.length === 0) return 'contract'

        return words
            .map((word, index) => {
                const lower = word.toLowerCase()
                return index === 0 ? lower : lower.charAt(0).toUpperCase() + lower.slice(1)
            })
            .join('')
    }

    /**
     * Extract chain ID from network name
     * This is a simple implementation, can be enhanced
     */
    private getChainIdFromNetwork(network: string): number {
        const networkMap: Record<string, number> = {
            mainnet: 1,
            ethereum: 1,
            goerli: 5,
            sepolia: 11155111,
            polygon: 137,
            mumbai: 80001,
            arbitrum: 42161,
            optimism: 10,
            base: 8453,
            bsc: 56,
            avalanche: 43114,
        }

        const normalized = network.toLowerCase()
        return networkMap[normalized] || parseInt(network, 10) || 1
    }
}

